"""Created location column on Store and removed enabled

Revision ID: 72fe99a6bf4d
Revises: 
Create Date: 2025-05-05 23:07:16.800353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72fe99a6bf4d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'owner')
    op.drop_column('stores', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('stores', sa.Column('owner', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
