"""Created owner_id column Stores

Revision ID: f9dbad086057
Revises: 72fe99a6bf4d
Create Date: 2025-05-09 23:06:38.993312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9dbad086057'
down_revision: Union[str, None] = '72fe99a6bf4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'stores', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_column('stores', 'owner_id')
    # ### end Alembic commands ###
